### ISSUE TITLE
Right now, this repo is not necessary anymore!

### ISSUE THREAD

**Issue by giacomocerquone** [neutralvibes/pi-cups#1]

**Comment by neutralvibes** [comment]
Thank you for your issue. It would have been nice to provide some detail with your conclusion however. Whether required on the latest distributions or not, it may still be useful to others for various reasons.

**Comment by giacomocerquone** [comment]
Ouch didn't notice the message wasn't actually posted to GitHub 🤦

Basically just installing cups over a raspbian distro in a raspberry and giving it the ppd file found already in the gitlab repo, the m2020 printer works just fine
